name: Louren van Garderen
favicon: null
layout_spectrum: 0.3587962272576988
typography_spectrum: 0.4351859297603369
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3897d0'
    - '#ffffff'
    - '#61b0dc'
    - '#cfedff'
    - '#9ec4e0'
  brandStrength: 0.1875
  lightness: 0.39288557693362236
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
